{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a32d42ee-3ec4-45ce-b7e2-adb0606c9d06",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q1. What is Exception in python? Write the difference between Exception SyntaxErrors?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "97779489-bc65-4574-a332-10ddce2d2686",
   "metadata": {},
   "outputs": [],
   "source": [
    "import logging"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "3d9ce1b6-4cc8-48a2-b558-c0847355a30d",
   "metadata": {},
   "outputs": [],
   "source": [
    "logging.basicConfig(filename= \"exp.er\" , level= logging.DEBUG)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "267b69e2-4e55-498f-8866-a398f3a51a3a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'Exception is the base class for all exceptions.exceptions are raised when some internal events occur which changes the normal flow of program.'"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\"\"\"Exception is the base class for all exceptions.exceptions are raised when some internal events occur which changes the normal flow of program.\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "664e81f9-4b23-40ad-ab2b-56fd56ba4165",
   "metadata": {},
   "outputs": [],
   "source": [
    "#with logging module\n",
    "logging.info(\"Exception is the base class for all exceptions.exceptions are raised when some internal events occur which changes the normal flow of program. \") "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "c8dfc1bc-2626-471d-af15-7466716fbaa5",
   "metadata": {},
   "outputs": [],
   "source": [
    "logging.error(\"SyntaxErrors:- SyntaxErrors are mistakes in the source code,such as Spelling and punctuation errors,incorrectlabels,and so on,which cause an error message to be generated by the compiler.Errors are the problems in a program due to which the program will stop the execution.Exceptions:-Even if a statement or expression is syntactically correct, it may cause an error when an attempt is made to execute it. Errors detected during execution are called exceptions and are not unconditionally fatal\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "cc6059f3-8774-4a80-a910-9b9760259d55",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'#SyntaxErrors:- SyntaxErrors are mistakes in the source code,such as Spelling and punctuation errors,incorrectlabels,and so on,which cause an error message to be generated by the compiler.Errors are the problems in a program due to which the program will stop the execution.\\n\\n###Exceptions:-Even if a statement or expression is syntactically correct, it may cause an error when an attempt is made to execute it. Errors detected during execution are called exceptions and are not unconditionally fatal: '"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\"\"\"#SyntaxErrors:- SyntaxErrors are mistakes in the source code,such as Spelling and punctuation errors,incorrectlabels,and so on,which cause an error message to be generated by the compiler.Errors are the problems in a program due to which the program will stop the execution.\n",
    "###Exceptions:-Even if a statement or expression is syntactically correct, it may cause an error when an attempt is made to execute it. Errors detected during execution are called exceptions and are not unconditionally fatal: \"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8bfbb0a1-0bf3-413d-9507-7ff899533498",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "88a4f99e-c0d3-43eb-88f6-da82be80a32b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3f9238dc-b646-4f91-8a95-56675f44f883",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q2. What happens when an exception is not handled? Explain with an example?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "2ab515b0-c5e0-4809-9efe-1699a4b65115",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'the runtime system will abort the program (i.e. crash) and an exception message will print to the console that caused the exception will not get executed.'"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\"\"\"the runtime system will abort the program (i.e. crash) and an exception message will print to the console that caused the exception will not get executed.\"\"\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "1ce0420d-7990-47cd-b2c5-ccba6d29ec1a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#with logging module\n",
    "logging.info(\"the runtime system will abort the program (i.e. crash) and an exception message will print to the console that caused the exception will not get executed.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "aab11151-123d-4c78-81b4-7064aef4008b",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'samidha'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[23], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m#example of Exeption\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01msamidha\u001b[39;00m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'samidha'"
     ]
    }
   ],
   "source": [
    "#example of Exeption\n",
    "import samidha\n",
    "#This gave me error because there is No module named a 'samidha' hence"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "2005fe6d-2127-4198-a4d8-3427b603ea76",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No module named 'samidha'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import samidha\n",
    "except ModuleNotFoundError as a :\n",
    "    print(a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "436e27aa-a5bf-4e68-a955-083ed5ae8050",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q3. Which Python statements are used to catch and handled by exceptions?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "81982356-2e4e-496e-927a-239abeed20aa",
   "metadata": {},
   "outputs": [],
   "source": [
    "# try and except block"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "ebd23b48-7806-44aa-8250-bab4ebd934d1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "'str' object has no attribute 'test'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    \"samidha\".test()\n",
    "except Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "d36c12bc-a647-45f3-a4da-705bda9020e2",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q4 expain with example\n",
    "#try and else\n",
    "#finally\n",
    "#raise"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "3a2c8e41-ade1-41d8-bf56-0153263f3d90",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "try block will executed\n",
      "else executed because try successfully work \n"
     ]
    }
   ],
   "source": [
    "#try and else= try block is not giving problem hence executed and hence else too.\n",
    "#because try successfully work  except will not get executed\n",
    "try:\n",
    "  print(\"try block will executed\")\n",
    "except:\n",
    "  print(\"except block will not show msg\")\n",
    "else:\n",
    "  print(\"else executed because try successfully work \")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "55dd8738-ec45-4ce0-9bf0-80b9acffa1ff",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "this will executed\n",
      "will get executed in any situation\n"
     ]
    }
   ],
   "source": [
    "#finally = will get executedin any situation\n",
    "try:\n",
    "    a= 10/0\n",
    "except ZeroDivisionError as z:\n",
    "    print(\"this will executed\")\n",
    "finally :\n",
    "    print(\"will get executed in any situation\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "id": "da4a6125-34f0-4242-91bb-c76bc33b76a9",
   "metadata": {},
   "outputs": [
    {
     "ename": "Exception",
     "evalue": "Sorry, no numbers below zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mException\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[60], line 5\u001b[0m\n\u001b[1;32m      2\u001b[0m x \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m x \u001b[38;5;241m<\u001b[39m \u001b[38;5;241m0\u001b[39m:\n\u001b[0;32m----> 5\u001b[0m   \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mSorry, no numbers below zero\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mException\u001b[0m: Sorry, no numbers below zero"
     ]
    }
   ],
   "source": [
    "#raise= x is less than 0  hence it raise the exepton error\n",
    "x = -1\n",
    "\n",
    "if x < 0:\n",
    "  raise Exception(\"Sorry, no numbers below zero\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "id": "756fa409-d1c5-4811-830d-800267ca7ccd",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "Only integers are allowed",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[61], line 4\u001b[0m\n\u001b[1;32m      1\u001b[0m x \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhello\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mtype\u001b[39m(x) \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m----> 4\u001b[0m   \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mOnly integers are allowed\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mTypeError\u001b[0m: Only integers are allowed"
     ]
    }
   ],
   "source": [
    "x = \"hello\"\n",
    "\n",
    "if not type(x) is int:\n",
    "  raise TypeError(\"Only integers are allowed\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "90f10625-9451-4197-a86b-3b2b2cf01d5c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'Q5. What are Custom Exceptions in python? Why do we need Custom Exceptions? Explain with an exmple'"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\"\"\"Q5. What are Custom Exceptions in python? Why do we need Custom Exceptions? Explain with an exmple\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "375a91fd-0684-4258-bcfa-133511e5e036",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'we can define custom exceptions by creating a new class that is derived from the built-in Exception class'"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\"\"\"we can define custom exceptions by creating a new class that is derived from the built-in Exception class\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d1e73670-c91a-4035-9630-82234d6e0b42",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter a number:  12\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception occurred: Invalid Age\n"
     ]
    }
   ],
   "source": [
    "class InvalidAgeException(Exception):\n",
    "    \"Raised when the input value is less than 18\"\n",
    "    pass\n",
    "\n",
    "#you need to guess this number\n",
    "number = 18\n",
    "\n",
    "try:\n",
    "    input_num = int(input(\"Enter a number: \"))\n",
    "    if input_num < number:\n",
    "        raise InvalidAgeException\n",
    "    else:\n",
    "        print(\"Eligible to Vote\")\n",
    "        \n",
    "except InvalidAgeException:\n",
    "    print(\"Exception occurred: Invalid Age\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c9d44c8f-713c-448f-9604-33af8b320814",
   "metadata": {},
   "outputs": [],
   "source": [
    "class bankac(Exception): \n",
    "    pass\n",
    "def __init__(self, msg):\n",
    "    self.msg = msg\n",
    "    \n",
    "    \n",
    "def checkbalance(money):\n",
    "    if balance <100:\n",
    "        raise bankac(\"you can't withdraw money\")\n",
    "    elif balance > 5000:\n",
    "        raise bankac(\"save money\")\n",
    "    else :\n",
    "        print(\"you have your money\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e7064abb-9e4a-46b7-9b2c-1fe8e0bdf1d8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "enter your amount 234\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    money = int(input(\"enter your amount\"))\n",
    "    bankac(money)\n",
    "except bankac as a:\n",
    "        print(a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "19dd5f43-f06a-4fc7-87ad-8ace7ae89a0f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c294eac0-0b3c-4519-959c-411e9c7a66dc",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "id": "35d5862a-5cd0-4f2d-845c-fc0e0680d270",
   "metadata": {},
   "outputs": [],
   "source": [
    "logging.info(\" Python, we can define custom exceptions by creating a new class that is derived from the built-in Exception class.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "id": "7f8beb46-42ea-4b4f-8af0-11927f3155a3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Python, we can define custom exceptions by creating a new class that is derived from the built-in Exception class."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "25c36869-c4d8-4053-8756-b8a155fceff0",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q6. Create custom exception class Use this class to handle an exception."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "954d2a2a-2c19-4b91-b1a3-1841fe3005df",
   "metadata": {},
   "outputs": [],
   "source": [
    "class customexception(Exception):\n",
    "    pass\n",
    "class dobexception(customexception):\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "501c6bd2-b62b-4ae5-90a0-a2d82f13d274",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "enter your age 43\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "age is invalid\n"
     ]
    }
   ],
   "source": [
    "year= int(input(\"enter your age\"))\n",
    "age = 2023 - year\n",
    "try:\n",
    "    if age <=30 & age > 20:\n",
    "        print(\"the age is valid\")\n",
    "    else:\n",
    "        raise dobexception\n",
    "except dobexception:\n",
    "    print(\"age is invalid\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6d4e403f-f6b7-4111-a401-01b2ff7e086d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
